SELECT 
CASE 
WHEN GRADES.GRADE >=8 THEN STUDENTS.NAME 
-- If not then NULL is given as the NAME 
ELSE NULL END AS NAME 
,GRADES.GRADE, STUDENTS.MARKS
FROM GRADES, STUDENTS

-- STU
WHERE STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME;
