/* 
https://leetcode.com/problems/employees-with-missing-information/
*/

SELECT EMPLOYEE_ID
FROM EMPLOYEES 
WHERE EMPLOYEE_ID NOT IN 
(
SELECT EMPLOYEE_ID 
FROM SALARY   )
UNION 

SELECT EMPLOYEE_ID 
FROM SALARY 
WHERE EMPLOYEE_ID 
NOT IN 
(SELECT EMPLOYEE_ID 
FROM EMPLOYEES)